name = "test-astr-react19-cf-workers"
main = "dist/_worker.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-12-20"
assets = { directory = "./dist/" }

[observability.logs]
enabled = true
